// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_startButton = NULL;
lv_obj_t * ui_startLabel = NULL;
lv_obj_t * ui_settings = NULL;
lv_obj_t * ui_settingsLabel = NULL;
lv_obj_t * ui_stopButton = NULL;
lv_obj_t * ui_stopLabel = NULL;
// event funtions
void ui_event_startButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        startButtonListener(e);
    }
}

void ui_event_settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_stepper1Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_stepper1Screen_screen_init);
    }
}

void ui_event_stopButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        stopButtonListener(e);
    }
}

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Home, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Home, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Home, lv_color_hex(0xCAB100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Home, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Home, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startButton = lv_btn_create(ui_Home);
    lv_obj_set_width(ui_startButton, 248);
    lv_obj_set_height(ui_startButton, 75);
    lv_obj_set_align(ui_startButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_startButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_startButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_startButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_startButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_startButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_startButton, lv_color_hex(0xCAB100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_startButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_startButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_startButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_startButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startLabel = lv_label_create(ui_startButton);
    lv_obj_set_width(ui_startLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_startLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_startLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_startLabel, "Start");
    lv_obj_set_style_text_color(ui_startLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_startLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_startLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_startLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings = lv_btn_create(ui_Home);
    lv_obj_set_width(ui_settings, 252);
    lv_obj_set_height(ui_settings, 92);
    lv_obj_set_x(ui_settings, 0);
    lv_obj_set_y(ui_settings, -82);
    lv_obj_set_align(ui_settings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsLabel = lv_label_create(ui_settings);
    lv_obj_set_width(ui_settingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settingsLabel, 0);
    lv_obj_set_y(ui_settingsLabel, 6);
    lv_obj_set_align(ui_settingsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settingsLabel, "Settings");
    lv_obj_set_style_text_font(ui_settingsLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stopButton = lv_btn_create(ui_Home);
    lv_obj_set_width(ui_stopButton, 225);
    lv_obj_set_height(ui_stopButton, 76);
    lv_obj_set_x(ui_stopButton, 0);
    lv_obj_set_y(ui_stopButton, 75);
    lv_obj_set_align(ui_stopButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stopButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_stopButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_stopButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stopButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stopLabel = lv_label_create(ui_stopButton);
    lv_obj_set_width(ui_stopLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stopLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_stopLabel, 0);
    lv_obj_set_y(ui_stopLabel, 1);
    lv_obj_set_align(ui_stopLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stopLabel, "Stop");
    lv_obj_set_style_text_color(ui_stopLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_stopLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_stopLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_startButton, ui_event_startButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settings, ui_event_settings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_stopButton, ui_event_stopButton, LV_EVENT_ALL, NULL);

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    ui_Home = NULL;
    ui_startButton = NULL;
    ui_startLabel = NULL;
    ui_settings = NULL;
    ui_settingsLabel = NULL;
    ui_stopButton = NULL;
    ui_stopLabel = NULL;

}
