// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_stepper1Screen = NULL;
lv_obj_t *ui_stepper1Button = NULL;
lv_obj_t *ui_stepper1Label = NULL;
lv_obj_t *ui_stepper1UpButton = NULL;
lv_obj_t *ui_stepper1UpLabel = NULL;
lv_obj_t *ui_stepper1DownButton = NULL;
lv_obj_t *ui_stepper1DownLabel = NULL;
// event funtions
void ui_event_stepper1Button(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_RELEASED)
    {
        changestepper(e);
    }
    if (event_code == LV_EVENT_LONG_PRESSED)
    {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_stepper1UpButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_RELEASED)
    {
        incrementUp(e);
    }
}

void ui_event_stepper1DownButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_RELEASED)
    {
        decrementDown(e);
    }
}

// build funtions

void ui_stepper1Screen_screen_init(void)
{
    ui_stepper1Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_stepper1Screen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_stepper1Screen, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_stepper1Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stepper1Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_stepper1Screen, lv_color_hex(0xCAB100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_stepper1Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_stepper1Screen, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stepper1Button = lv_btn_create(ui_stepper1Screen);
    lv_obj_set_width(ui_stepper1Button, 247);
    lv_obj_set_height(ui_stepper1Button, 77);
    lv_obj_set_align(ui_stepper1Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stepper1Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_stepper1Button, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_stepper1Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stepper1Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_stepper1Button, lv_color_hex(0xCAB100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_stepper1Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_stepper1Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stepper1Label = lv_label_create(ui_stepper1Button);
    lv_obj_set_width(ui_stepper1Label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_stepper1Label, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_stepper1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stepper1Label, "Stepper1");
    lv_obj_set_style_text_font(ui_stepper1Label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stepper1UpButton = lv_btn_create(ui_stepper1Screen);
    lv_obj_set_width(ui_stepper1UpButton, 228);
    lv_obj_set_height(ui_stepper1UpButton, 80);
    lv_obj_set_x(ui_stepper1UpButton, 2);
    lv_obj_set_y(ui_stepper1UpButton, -79);
    lv_obj_set_align(ui_stepper1UpButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stepper1UpButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_stepper1UpButton, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_stepper1UpButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stepper1UpButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stepper1UpLabel = lv_label_create(ui_stepper1UpButton);
    lv_obj_set_width(ui_stepper1UpLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_stepper1UpLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_stepper1UpLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stepper1UpLabel, "-");
    lv_obj_set_style_text_font(ui_stepper1UpLabel, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stepper1DownButton = lv_btn_create(ui_stepper1Screen);
    lv_obj_set_width(ui_stepper1DownButton, 219);
    lv_obj_set_height(ui_stepper1DownButton, 77);
    lv_obj_set_x(ui_stepper1DownButton, 2);
    lv_obj_set_y(ui_stepper1DownButton, 76);
    lv_obj_set_align(ui_stepper1DownButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stepper1DownButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_stepper1DownButton, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_stepper1DownButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stepper1DownButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stepper1DownLabel = lv_label_create(ui_stepper1DownButton);
    lv_obj_set_width(ui_stepper1DownLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_stepper1DownLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_stepper1DownLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stepper1DownLabel, "-");
    lv_obj_set_style_text_font(ui_stepper1DownLabel, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_stepper1Button, ui_event_stepper1Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_stepper1UpButton, ui_event_stepper1UpButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_stepper1DownButton, ui_event_stepper1DownButton, LV_EVENT_ALL, NULL);
}

void ui_stepper1Screen_screen_destroy(void)
{
    if (ui_stepper1Screen)
        lv_obj_del(ui_stepper1Screen);

    // NULL screen variables
    ui_stepper1Screen = NULL;
    ui_stepper1Button = NULL;
    ui_stepper1Label = NULL;
    ui_stepper1UpButton = NULL;
    ui_stepper1UpLabel = NULL;
    ui_stepper1DownButton = NULL;
    ui_stepper1DownLabel = NULL;
}
