// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_STEPPER1SCREEN_H
#define UI_STEPPER1SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_stepper1Screen
extern void ui_stepper1Screen_screen_init(void);
extern void ui_stepper1Screen_screen_destroy(void);
extern lv_obj_t * ui_stepper1Screen;
extern void ui_event_stepper1Button(lv_event_t * e);
extern lv_obj_t * ui_stepper1Button;
extern lv_obj_t * ui_stepper1Label;
extern void ui_event_stepper1UpButton(lv_event_t * e);
extern lv_obj_t * ui_stepper1UpButton;
extern lv_obj_t * ui_stepper1UpLabel;
extern void ui_event_stepper1DownButton(lv_event_t * e);
extern lv_obj_t * ui_stepper1DownButton;
extern lv_obj_t * ui_stepper1DownLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

